services:
  tegami:
    build: .
    pull_policy: build
    restart: unless-stopped
    ports:
      - 127.0.0.1:${PORT}:3000
    volumes:
      - "./data:/app/data"
    environment:
      TEGAMI: ${TEGAMI}
      AUTH: ${AUTH}
